"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.courses = exports.specialties = exports.institutes = void 0;
exports.institutes = [
    {
        id: "infsp-adrar", name: "INFSPM ADRAR", type: "INFSPM", wilaya: "Adrar", location: "Adrar", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "manip-radio", "labo", "prep-pharma", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 13.4, targetWilaya: "Adrar" },
            { specialtyId: "isp", year: 2025, average: 12.09, targetWilaya: "Tamanrasset" },
            { specialtyId: "isp", year: 2025, average: 13.42, targetWilaya: "Timimoun" },
            { specialtyId: "isp", year: 2025, average: 10.33, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "isp", year: 2025, average: 11.27, targetWilaya: "In salah" },
            { specialtyId: "isp", year: 2025, average: 11.84, targetWilaya: "In guezzam" },
            { specialtyId: "kine", year: 2025, average: 14.71, targetWilaya: "Adrar" },
            { specialtyId: "kine", year: 2025, average: 14.21, targetWilaya: "Tamanrasset" },
            { specialtyId: "kine", year: 2025, average: 14.9, targetWilaya: "Timimoun" },
            { specialtyId: "kine", year: 2025, average: 0, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "kine", year: 2025, average: 12.31, targetWilaya: "In salah" },
            { specialtyId: "kine", year: 2025, average: 12.65, targetWilaya: "In guezzam" },
            { specialtyId: "manip-radio", year: 2025, average: 14.18, targetWilaya: "Adrar" },
            { specialtyId: "manip-radio", year: 2025, average: 13.36, targetWilaya: "Tamanrasset" },
            { specialtyId: "manip-radio", year: 2025, average: 13.9, targetWilaya: "Timimoun" },
            { specialtyId: "manip-radio", year: 2025, average: 0, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "manip-radio", year: 2025, average: 12.37, targetWilaya: "In salah" },
            { specialtyId: "manip-radio", year: 2025, average: 0, targetWilaya: "In guezzam" },
            { specialtyId: "labo", year: 2025, average: 14.59, targetWilaya: "Adrar" },
            { specialtyId: "labo", year: 2025, average: 12.87, targetWilaya: "Tamanrasset" },
            { specialtyId: "labo", year: 2025, average: 14.49, targetWilaya: "Timimoun" },
            { specialtyId: "labo", year: 2025, average: 12.45, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "labo", year: 2025, average: 12.42, targetWilaya: "In salah" },
            { specialtyId: "labo", year: 2025, average: 11.14, targetWilaya: "In guezzam" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.5, targetWilaya: "Adrar" },
            { specialtyId: "prep-pharma", year: 2025, average: 12.55, targetWilaya: "Tamanrasset" },
            { specialtyId: "prep-pharma", year: 2025, average: 13.43, targetWilaya: "Tindouf" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.59, targetWilaya: "Timimoun" },
            { specialtyId: "prep-pharma", year: 2025, average: 0, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "prep-pharma", year: 2025, average: 13.28, targetWilaya: "Beni abbes" },
            { specialtyId: "prep-pharma", year: 2025, average: 13.56, targetWilaya: "In salah" },
            { specialtyId: "prep-pharma", year: 2025, average: 0, targetWilaya: "In guezzam" },
            { specialtyId: "ass-med", year: 2025, average: 13.44, targetWilaya: "Adrar" },
            { specialtyId: "ass-med", year: 2025, average: 12.34, targetWilaya: "Tamanrasset" },
            { specialtyId: "ass-med", year: 2025, average: 13.58, targetWilaya: "Timimoun" },
            { specialtyId: "ass-med", year: 2025, average: 10.72, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "ass-med", year: 2025, average: 10.98, targetWilaya: "In salah" },
            { specialtyId: "ass-med", year: 2025, average: 10.6, targetWilaya: "In guezzam" },
        ]
    },
    {
        id: "infsp-batna", name: "INFSPM BATNA", type: "INFSPM", wilaya: "Batna", location: "Batna", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "ergo", "manip-radio", "labo", "prep-pharma", "hygiene", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.28, targetWilaya: "Oum-el bouaghi" },
            { specialtyId: "isp", year: 2025, average: 15.93, targetWilaya: "Batna" },
            { specialtyId: "kine", year: 2025, average: 16.28, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "kine", year: 2025, average: 16.79, targetWilaya: "Batna" },
            { specialtyId: "kine", year: 2025, average: 15.78, targetWilaya: "Tebessa" },
            { specialtyId: "kine", year: 2025, average: 16.58, targetWilaya: "Khenchla" },
            { specialtyId: "ergo", year: 2025, average: 15.55, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "ergo", year: 2025, average: 16.12, targetWilaya: "Batna" },
            { specialtyId: "ergo", year: 2025, average: 14.88, targetWilaya: "Tebessa" },
            { specialtyId: "ergo", year: 2025, average: 14.09, targetWilaya: "Ouargla" },
            { specialtyId: "ergo", year: 2025, average: 0, targetWilaya: "El oued" },
            { specialtyId: "ergo", year: 2025, average: 15.32, targetWilaya: "Khenchla" },
            { specialtyId: "ergo", year: 2025, average: 14.11, targetWilaya: "Touggourt" },
            { specialtyId: "ergo", year: 2025, average: 0, targetWilaya: "Djanet" },
            { specialtyId: "ergo", year: 2025, average: 14.08, targetWilaya: "El mghaier" },
            { specialtyId: "manip-radio", year: 2025, average: 15.73, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "manip-radio", year: 2025, average: 16.28, targetWilaya: "Batna" },
            { specialtyId: "labo", year: 2025, average: 15.6, targetWilaya: "Oum el-bouaghi" },
            { specialtyId: "labo", year: 2025, average: 16.28, targetWilaya: "Batna" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.63, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "prep-pharma", year: 2025, average: 16.43, targetWilaya: "Batna" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.83, targetWilaya: "Tebessa" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.67, targetWilaya: "Khenchla" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.31, targetWilaya: "El mghaier" },
            { specialtyId: "hygiene", year: 2025, average: 15.57, targetWilaya: "Oum el-bouaghi" },
            { specialtyId: "hygiene", year: 2025, average: 16.1, targetWilaya: "Batna" },
            { specialtyId: "hygiene", year: 2025, average: 14.53, targetWilaya: "Tebessa" },
            { specialtyId: "hygiene", year: 2025, average: 15.68, targetWilaya: "Setif" },
            { specialtyId: "hygiene", year: 2025, average: 15.67, targetWilaya: "Guelma" },
            { specialtyId: "hygiene", year: 2025, average: 15.63, targetWilaya: "Khenchla" },
            { specialtyId: "hygiene", year: 2025, average: 15.76, targetWilaya: "Mila" },
            { specialtyId: "ass-med", year: 2025, average: 14.82, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "ass-med", year: 2025, average: 15.77, targetWilaya: "Batna" },
            { specialtyId: "ass-med", year: 2025, average: 14.73, targetWilaya: "Mila" },
            { specialtyId: "ass-med", year: 2025, average: 12.94, targetWilaya: "El mghaier" },
        ]
    },
    {
        id: "infsp-bejaia", name: "INFSPM BEJAIA", type: "INFSPM", wilaya: "Béjaïa", location: "Béjaïa", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "labo", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 14.44, targetWilaya: "Bejaia" },
            { specialtyId: "isp", year: 2025, average: 14.45, targetWilaya: "Tizi ouzou" },
            { specialtyId: "labo", year: 2025, average: 15.37, targetWilaya: "Bejaia" },
            { specialtyId: "labo", year: 2025, average: 15.38, targetWilaya: "Bouira" },
            { specialtyId: "labo", year: 2025, average: 14.94, targetWilaya: "Tizi ouzou" },
            { specialtyId: "labo", year: 2025, average: 15.29, targetWilaya: "Boumerdes" },
            { specialtyId: "ass-med", year: 2025, average: 14.1, targetWilaya: "Bejaia" },
            { specialtyId: "ass-med", year: 2025, average: 14.42, targetWilaya: "Bouira" },
            { specialtyId: "ass-med", year: 2025, average: 14.33, targetWilaya: "Jijel" },
            { specialtyId: "ass-med", year: 2025, average: 15.05, targetWilaya: "Setif" },
            { specialtyId: "ass-med", year: 2025, average: 14.27, targetWilaya: "Bordj Bou Arreridj" },
            { specialtyId: "ass-soc", year: 2025, average: 13.99, targetWilaya: "Bejaia" },
            { specialtyId: "ass-soc", year: 2025, average: 13.91, targetWilaya: "Bouira" },
            { specialtyId: "ass-soc", year: 2025, average: 13.12, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "ass-soc", year: 2025, average: 14.25, targetWilaya: "Setif" },
            { specialtyId: "ass-soc", year: 2025, average: 0, targetWilaya: "Bordj Bou Arreridj" },
        ]
    },
    {
        id: "infsp-biskra", name: "INFSPM BISKRA", type: "INFSPM", wilaya: "Biskra", location: "Biskra", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "prothese", "kine", "manip-radio", "labo", "prep-pharma", "hygiene", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 14.79, targetWilaya: "Biskra" },
            { specialtyId: "isp", year: 2025, average: 14.94, targetWilaya: "El oued" },
            { specialtyId: "isp", year: 2025, average: 13.3, targetWilaya: "Ouled djellal" },
            { specialtyId: "isp", year: 2025, average: 13.24, targetWilaya: "El mghaier" },
            { specialtyId: "prothese", year: 2025, average: 15.6, targetWilaya: "Oum-el-bouaghi" },
            { specialtyId: "prothese", year: 2025, average: 15.98, targetWilaya: "Batna" },
            { specialtyId: "prothese", year: 2025, average: 15.83, targetWilaya: "Biskra" },
            { specialtyId: "prothese", year: 2025, average: 13.5, targetWilaya: "Tamanrasset" },
            { specialtyId: "prothese", year: 2025, average: 14.99, targetWilaya: "Tebessa" },
            { specialtyId: "prothese", year: 2025, average: 14.71, targetWilaya: "Ouargla" },
            { specialtyId: "prothese", year: 2025, average: 12.23, targetWilaya: "Illizi" },
            { specialtyId: "prothese", year: 2025, average: 15.91, targetWilaya: "El oued" },
            { specialtyId: "prothese", year: 2025, average: 15.23, targetWilaya: "Khenchla" },
            { specialtyId: "prothese", year: 2025, average: 14.53, targetWilaya: "Ouled djellal" },
            { specialtyId: "prothese", year: 2025, average: 13.57, targetWilaya: "In salah" },
            { specialtyId: "prothese", year: 2025, average: 14.13, targetWilaya: "In guezzam" },
            { specialtyId: "prothese", year: 2025, average: 15.54, targetWilaya: "Touggourt" },
            { specialtyId: "prothese", year: 2025, average: 0, targetWilaya: "Djanet" },
            { specialtyId: "kine", year: 2025, average: 16.25, targetWilaya: "Biskra" },
            { specialtyId: "kine", year: 2025, average: 16.18, targetWilaya: "El oued" },
            { specialtyId: "kine", year: 2025, average: 14.79, targetWilaya: "Ouled djellal" },
            { specialtyId: "kine", year: 2025, average: 15.98, targetWilaya: "Touggourt" },
            { specialtyId: "kine", year: 2025, average: 13.81, targetWilaya: "El mghaier" },
            { specialtyId: "manip-radio", year: 2025, average: 15.7, targetWilaya: "Biskra" },
            { specialtyId: "manip-radio", year: 2025, average: 14.34, targetWilaya: "Ouled djellal" },
            { specialtyId: "manip-radio", year: 2025, average: 14.15, targetWilaya: "El mghaier" },
            { specialtyId: "labo", year: 2025, average: 15.7, targetWilaya: "Biskra" },
            { specialtyId: "labo", year: 2025, average: 14.31, targetWilaya: "Ouled djellal" },
            { specialtyId: "labo", year: 2025, average: 14.29, targetWilaya: "El mghaier" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.31, targetWilaya: "Biskra" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.92, targetWilaya: "El oued" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.19, targetWilaya: "Ouled djellal" },
            { specialtyId: "prep-pharma", year: 2025, average: 14.69, targetWilaya: "Touggourt" },
            { specialtyId: "hygiene", year: 2025, average: 15.01, targetWilaya: "Biskra" },
            { specialtyId: "hygiene", year: 2025, average: 14.72, targetWilaya: "El oued" },
            { specialtyId: "hygiene", year: 2025, average: 14.22, targetWilaya: "Ouled djellal" },
            { specialtyId: "hygiene", year: 2025, average: 14.12, targetWilaya: "Touggourt" },
            { specialtyId: "hygiene", year: 2025, average: 13.6, targetWilaya: "El mghaier" },
            { specialtyId: "ass-med", year: 2025, average: 15.54, targetWilaya: "Biskra" },
            { specialtyId: "ass-med", year: 2025, average: 13.15, targetWilaya: "El oued" },
            { specialtyId: "ass-med", year: 2025, average: 13.54, targetWilaya: "Ouled djellal" },
            { specialtyId: "ass-med", year: 2025, average: 14.46, targetWilaya: "Touggourt" },
        ]
    },
    {
        id: "infsp-bechar", name: "INFSPM BECHAR", type: "INFSPM", wilaya: "Béchar", location: "Béchar", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "manip-radio", "labo", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 13.53, targetWilaya: "Bechar" },
            { specialtyId: "isp", year: 2025, average: 12.16, targetWilaya: "Tindouf" },
            { specialtyId: "isp", year: 2025, average: 11.59, targetWilaya: "Beni abbes" },
            { specialtyId: "kine", year: 2025, average: 15.76, targetWilaya: "Bechar" },
            { specialtyId: "kine", year: 2025, average: 15.4, targetWilaya: "El bayadh" },
            { specialtyId: "kine", year: 2025, average: 14.32, targetWilaya: "Tindouf" },
            { specialtyId: "kine", year: 2025, average: 12.5, targetWilaya: "Beni abbes" },
            { specialtyId: "manip-radio", year: 2025, average: 15.01, targetWilaya: "Bechar" },
            { specialtyId: "manip-radio", year: 2025, average: 13.62, targetWilaya: "Tindouf" },
            { specialtyId: "manip-radio", year: 2025, average: 12.14, targetWilaya: "Beni abbes" },
            { specialtyId: "labo", year: 2025, average: 14.95, targetWilaya: "Bechar" },
            { specialtyId: "labo", year: 2025, average: 14.36, targetWilaya: "Tindouf" },
            { specialtyId: "labo", year: 2025, average: 13.16, targetWilaya: "Beni abbes" },
            { specialtyId: "ass-med", year: 2025, average: 13.52, targetWilaya: "Bechar" },
            { specialtyId: "ass-med", year: 2025, average: 11.93, targetWilaya: "Tindouf" },
            { specialtyId: "ass-med", year: 2025, average: 12.15, targetWilaya: "Beni abbes" },
            { specialtyId: "ass-soc", year: 2025, average: 13.13, targetWilaya: "Adrar" },
            { specialtyId: "ass-soc", year: 2025, average: 13.49, targetWilaya: "Bechar" },
            { specialtyId: "ass-soc", year: 2025, average: 13.88, targetWilaya: "Tindouf" },
            { specialtyId: "ass-soc", year: 2025, average: 13.85, targetWilaya: "Timimoun" },
            { specialtyId: "ass-soc", year: 2025, average: 0, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "ass-soc", year: 2025, average: 12.31, targetWilaya: "Beni abbes" },
        ]
    },
    {
        id: "infsp-blida", name: "INFSPM BLIDA", type: "INFSPM", wilaya: "Blida", location: "Blida", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "prothese", "kine", "ergo", "psycho", "manip-radio", "labo", "prep-pharma", "hygiene"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.29, targetWilaya: "Blida" },
            { specialtyId: "isp", year: 2025, average: 15.12, targetWilaya: "Tipaza" },
            { specialtyId: "prothese", year: 2025, average: 15.22, targetWilaya: "Laghouat" },
            { specialtyId: "prothese", year: 2025, average: 16.28, targetWilaya: "Blida" },
            { specialtyId: "prothese", year: 2025, average: 15.53, targetWilaya: "Bouira" },
            { specialtyId: "prothese", year: 2025, average: 15.78, targetWilaya: "Tiaret" },
            { specialtyId: "prothese", year: 2025, average: 15.64, targetWilaya: "Djelfa" },
            { specialtyId: "prothese", year: 2025, average: 15.9, targetWilaya: "Medea" },
            { specialtyId: "prothese", year: 2025, average: 16.09, targetWilaya: "Msila" },
            { specialtyId: "prothese", year: 2025, average: 16.1, targetWilaya: "Tissemsilt" },
            { specialtyId: "prothese", year: 2025, average: 16.24, targetWilaya: "Tipaza" },
            { specialtyId: "prothese", year: 2025, average: 16.07, targetWilaya: "Ain Defla" },
            { specialtyId: "prothese", year: 2025, average: 15.98, targetWilaya: "Ghardaia" },
            { specialtyId: "prothese", year: 2025, average: 12.88, targetWilaya: "El meniaa" },
            { specialtyId: "kine", year: 2025, average: 16.27, targetWilaya: "Laghouat" },
            { specialtyId: "kine", year: 2025, average: 16.26, targetWilaya: "Blida" },
            { specialtyId: "kine", year: 2025, average: 16.19, targetWilaya: "Djelfa" },
            { specialtyId: "kine", year: 2025, average: 16.55, targetWilaya: "Medea" },
            { specialtyId: "kine", year: 2025, average: 16.57, targetWilaya: "Ain Defla" },
            { specialtyId: "ergo", year: 2025, average: 14.59, targetWilaya: "Laghouat" },
            { specialtyId: "ergo", year: 2025, average: 15.35, targetWilaya: "Blida" },
            { specialtyId: "ergo", year: 2025, average: 14.97, targetWilaya: "Bouira" },
            { specialtyId: "ergo", year: 2025, average: 15.09, targetWilaya: "Medea" },
            { specialtyId: "ergo", year: 2025, average: 14.98, targetWilaya: "Tipaza" },
            { specialtyId: "ergo", year: 2025, average: 15.47, targetWilaya: "Ain Defla" },
            { specialtyId: "ergo", year: 2025, average: 14.29, targetWilaya: "Ghardaia" },
            { specialtyId: "ergo", year: 2025, average: 12.8, targetWilaya: "El meniaa" },
            { specialtyId: "psycho", year: 2025, average: 14.1, targetWilaya: "Laghouat" },
            { specialtyId: "psycho", year: 2025, average: 15.21, targetWilaya: "Blida" },
            { specialtyId: "psycho", year: 2025, average: 14.57, targetWilaya: "Bouira" },
            { specialtyId: "psycho", year: 2025, average: 15.37, targetWilaya: "Tissemsilt" },
            { specialtyId: "psycho", year: 2025, average: 15.38, targetWilaya: "Tipaza" },
            { specialtyId: "psycho", year: 2025, average: 15.16, targetWilaya: "Ghardaia" },
            { specialtyId: "psycho", year: 2025, average: 12.97, targetWilaya: "Timimoun" },
            { specialtyId: "manip-radio", year: 2025, average: 15.91, targetWilaya: "Blida" },
            { specialtyId: "manip-radio", year: 2025, average: 16.08, targetWilaya: "Tipaza" },
            { specialtyId: "labo", year: 2025, average: 15.96, targetWilaya: "Blida" },
            { specialtyId: "labo", year: 2025, average: 15.77, targetWilaya: "Tipaza" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.7, targetWilaya: "Blida" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.3, targetWilaya: "Bouira" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.58, targetWilaya: "Tipaza" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.71, targetWilaya: "Ain Defla" },
            { specialtyId: "hygiene", year: 2025, average: 15.38, targetWilaya: "Blida" },
            { specialtyId: "hygiene", year: 2025, average: 15.35, targetWilaya: "Djelfa" },
            { specialtyId: "hygiene", year: 2025, average: 15.23, targetWilaya: "Medea" },
            { specialtyId: "hygiene", year: 2025, average: 15.45, targetWilaya: "Ain Defla" },
        ]
    },
    {
        id: "infsp-bouira", name: "INFSPM BOUIRA", type: "INFSPM", wilaya: "Bouira", location: "Bouira", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "hygiene"], averages: [
            { specialtyId: "isp", year: 2025, average: 14.72, targetWilaya: "Bouira" },
            { specialtyId: "isp", year: 2025, average: 14.94, targetWilaya: "Boumerdes" },
            { specialtyId: "manip-radio", year: 2025, average: 14.9, targetWilaya: "Bejaia" },
            { specialtyId: "manip-radio", year: 2025, average: 15.4, targetWilaya: "Bouira" },
            { specialtyId: "manip-radio", year: 2025, average: 14.98, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "manip-radio", year: 2025, average: 15.57, targetWilaya: "Boumerdes" },
            { specialtyId: "hygiene", year: 2025, average: 14.26, targetWilaya: "Bejaia" },
            { specialtyId: "hygiene", year: 2025, average: 15.07, targetWilaya: "Bouira" },
            { specialtyId: "hygiene", year: 2025, average: 15.58, targetWilaya: "Msila" },
            { specialtyId: "hygiene", year: 2025, average: 15.45, targetWilaya: "Bordj Bou Arreridj" },
        ]
    },
    {
        id: "infsp-tebessa", name: "INFSPM TEBESSA", type: "INFSPM", wilaya: "Tébessa", location: "Tébessa", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 14.27, targetWilaya: "Tebessa" },
            { specialtyId: "isp", year: 2025, average: 15, targetWilaya: "Khenchla" },
            { specialtyId: "manip-radio", year: 2025, average: 15.12, targetWilaya: "Tebessa" },
            { specialtyId: "manip-radio", year: 2025, average: 15.13, targetWilaya: "El oued" },
            { specialtyId: "labo", year: 2025, average: 14.88, targetWilaya: "Tebessa" },
            { specialtyId: "labo", year: 2025, average: 15.17, targetWilaya: "El oued" },
            { specialtyId: "labo", year: 2025, average: 15.63, targetWilaya: "Khenchla" },
            { specialtyId: "ass-med", year: 2025, average: 13.68, targetWilaya: "Tebessa" },
            { specialtyId: "ass-med", year: 2025, average: 14.44, targetWilaya: "Guelma" },
            { specialtyId: "ass-med", year: 2025, average: 14.52, targetWilaya: "Khenchla" },
            { specialtyId: "ass-med", year: 2025, average: 15.5, targetWilaya: "Souk ahras" },
        ]
    },
    {
        id: "infsp-tiaret", name: "INFSPM TIARET", type: "INFSPM", wilaya: "Tiaret", location: "Tiaret", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "hygiene", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.38, targetWilaya: "Tiaret" },
            { specialtyId: "isp", year: 2025, average: 14.17, targetWilaya: "El bayadh" },
            { specialtyId: "isp", year: 2025, average: 14.97, targetWilaya: "Tissemsilt" },
            { specialtyId: "manip-radio", year: 2025, average: 16, targetWilaya: "Tiaret" },
            { specialtyId: "manip-radio", year: 2025, average: 14.66, targetWilaya: "El bayadh" },
            { specialtyId: "manip-radio", year: 2025, average: 15.73, targetWilaya: "Tissemsilt" },
            { specialtyId: "labo", year: 2025, average: 16.12, targetWilaya: "Tiaret" },
            { specialtyId: "labo", year: 2025, average: 15, targetWilaya: "El bayadh" },
            { specialtyId: "labo", year: 2025, average: 15.67, targetWilaya: "Tissemsilt" },
            { specialtyId: "hygiene", year: 2025, average: 13.1, targetWilaya: "Adrar" },
            { specialtyId: "hygiene", year: 2025, average: 14.6, targetWilaya: "Laghouat" },
            { specialtyId: "hygiene", year: 2025, average: 15.76, targetWilaya: "Tiaret" },
            { specialtyId: "hygiene", year: 2025, average: 14.28, targetWilaya: "Tindouf" },
            { specialtyId: "hygiene", year: 2025, average: 0, targetWilaya: "Bordj badji mokhtar" },
            { specialtyId: "hygiene", year: 2025, average: 11.58, targetWilaya: "Beni abbes" },
            { specialtyId: "ass-med", year: 2025, average: 13.7, targetWilaya: "Laghouat" },
            { specialtyId: "ass-med", year: 2025, average: 14.93, targetWilaya: "Tiaret" },
            { specialtyId: "ass-med", year: 2025, average: 14.54, targetWilaya: "Tissemsilt" },
        ]
    },
    {
        id: "infsp-alger", name: "INFSPM ALGER", type: "INFSPM", wilaya: "Alger", location: "Alger", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "diet", "prothese", "kine", "podo", "ergo", "ortho-app", "psycho", "manip-radio", "labo", "prep-pharma", "hygiene", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.14, targetWilaya: "Alger" },
            { specialtyId: "diet", year: 2025, average: 16.23, targetWilaya: "Laghouat" },
            { specialtyId: "diet", year: 2025, average: 16.02, targetWilaya: "Bejaia" },
            { specialtyId: "diet", year: 2025, average: 16.24, targetWilaya: "Blida" },
            { specialtyId: "diet", year: 2025, average: 15.89, targetWilaya: "Bouira" },
            { specialtyId: "diet", year: 2025, average: 15.03, targetWilaya: "Tizi ouzou" },
            { specialtyId: "diet", year: 2025, average: 16.34, targetWilaya: "Alger" },
            { specialtyId: "diet", year: 2025, average: 16.08, targetWilaya: "Djelfa" },
            { specialtyId: "diet", year: 2025, average: 16.29, targetWilaya: "Medea" },
            { specialtyId: "diet", year: 2025, average: 15.94, targetWilaya: "Msila" },
            { specialtyId: "diet", year: 2025, average: 15.95, targetWilaya: "Bordj Bou Arreridj" },
            { specialtyId: "diet", year: 2025, average: 16.43, targetWilaya: "Boumerdes" },
            { specialtyId: "diet", year: 2025, average: 16.47, targetWilaya: "Tipaza" },
            { specialtyId: "diet", year: 2025, average: 16.12, targetWilaya: "Ain Defla" },
            { specialtyId: "prothese", year: 2025, average: 15.42, targetWilaya: "Bejaia" },
            { specialtyId: "prothese", year: 2025, average: 15.35, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "prothese", year: 2025, average: 16.45, targetWilaya: "Alger" },
            { specialtyId: "prothese", year: 2025, average: 15.73, targetWilaya: "Jijel" },
            { specialtyId: "prothese", year: 2025, average: 15.73, targetWilaya: "Setif" },
            { specialtyId: "prothese", year: 2025, average: 16.07, targetWilaya: "Skikda" },
            { specialtyId: "prothese", year: 2025, average: 15.53, targetWilaya: "Annaba" },
            { specialtyId: "prothese", year: 2025, average: 16.02, targetWilaya: "Guelma" },
            { specialtyId: "prothese", year: 2025, average: 15.88, targetWilaya: "Constantine" },
            { specialtyId: "prothese", year: 2025, average: 16.12, targetWilaya: "Bordj Bou Arreridj" },
            { specialtyId: "prothese", year: 2025, average: 16.43, targetWilaya: "Boumerdes" },
            { specialtyId: "prothese", year: 2025, average: 15.51, targetWilaya: "Eltarf" },
            { specialtyId: "prothese", year: 2025, average: 16.03, targetWilaya: "Souk ahras" },
            { specialtyId: "prothese", year: 2025, average: 16.5, targetWilaya: "Mila" },
            { specialtyId: "kine", year: 2025, average: 16.57, targetWilaya: "Bouira" },
            { specialtyId: "kine", year: 2025, average: 16.14, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "kine", year: 2025, average: 16.7, targetWilaya: "Alger" },
            { specialtyId: "kine", year: 2025, average: 16.62, targetWilaya: "Boumerdes" },
            { specialtyId: "kine", year: 2025, average: 16.37, targetWilaya: "Tipaza" },
            { specialtyId: "podo", year: 2025, average: 14.4, targetWilaya: "Laghouat" },
            { specialtyId: "podo", year: 2025, average: 13.66, targetWilaya: "Bechar" },
            { specialtyId: "podo", year: 2025, average: 14.21, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "podo", year: 2025, average: 14.97, targetWilaya: "Alger" },
            { specialtyId: "podo", year: 2025, average: 15.41, targetWilaya: "Setif" },
            { specialtyId: "podo", year: 2025, average: 15.11, targetWilaya: "Sidibel-abbes" },
            { specialtyId: "podo", year: 2025, average: 14.82, targetWilaya: "Annaba" },
            { specialtyId: "podo", year: 2025, average: 14.95, targetWilaya: "Constantine" },
            { specialtyId: "podo", year: 2025, average: 13.08, targetWilaya: "Ouargla" },
            { specialtyId: "podo", year: 2025, average: 14.72, targetWilaya: "Oran" },
            { specialtyId: "ergo", year: 2025, average: 13.63, targetWilaya: "Adrar" },
            { specialtyId: "ergo", year: 2025, average: 12.71, targetWilaya: "Tamanrasset" },
            { specialtyId: "ergo", year: 2025, average: 14.53, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "ergo", year: 2025, average: 15.4, targetWilaya: "Alger" },
            { specialtyId: "ergo", year: 2025, average: 15.4, targetWilaya: "Boumerdes" },
            { specialtyId: "ergo", year: 2025, average: 13.19, targetWilaya: "Timimoun" },
            { specialtyId: "ergo", year: 2025, average: 12.39, targetWilaya: "In salah" },
            { specialtyId: "ergo", year: 2025, average: 0, targetWilaya: "In guezzam" },
            { specialtyId: "ortho-app", year: 2025, average: 14.72, targetWilaya: "Laghouat" },
            { specialtyId: "ortho-app", year: 2025, average: 15.63, targetWilaya: "Bouira" },
            { specialtyId: "ortho-app", year: 2025, average: 13.88, targetWilaya: "Tamanrasset" },
            { specialtyId: "ortho-app", year: 2025, average: 14.47, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "ortho-app", year: 2025, average: 15.72, targetWilaya: "Alger" },
            { specialtyId: "ortho-app", year: 2025, average: 15.61, targetWilaya: "Medea" },
            { specialtyId: "ortho-app", year: 2025, average: 11.95, targetWilaya: "Illizi" },
            { specialtyId: "ortho-app", year: 2025, average: 15.09, targetWilaya: "Boumerdes" },
            { specialtyId: "ortho-app", year: 2025, average: 13.19, targetWilaya: "In salah" },
            { specialtyId: "ortho-app", year: 2025, average: 0, targetWilaya: "Djanet" },
            { specialtyId: "psycho", year: 2025, average: 13.19, targetWilaya: "Adrar" },
            { specialtyId: "psycho", year: 2025, average: 12.57, targetWilaya: "Tamanrasset" },
            { specialtyId: "psycho", year: 2025, average: 14.36, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "psycho", year: 2025, average: 15.86, targetWilaya: "Alger" },
            { specialtyId: "psycho", year: 2025, average: 12.87, targetWilaya: "Ouargla" },
            { specialtyId: "psycho", year: 2025, average: 13.58, targetWilaya: "Illizi" },
            { specialtyId: "psycho", year: 2025, average: 15.36, targetWilaya: "Boumerdes" },
            { specialtyId: "psycho", year: 2025, average: 11.97, targetWilaya: "In salah" },
            { specialtyId: "psycho", year: 2025, average: 12.48, targetWilaya: "In guezzam" },
            { specialtyId: "psycho", year: 2025, average: 0, targetWilaya: "Djanet" },
            { specialtyId: "manip-radio", year: 2025, average: 15.97, targetWilaya: "Alger" },
            { specialtyId: "labo", year: 2025, average: 15.96, targetWilaya: "Alger" },
            { specialtyId: "prep-pharma", year: 2025, average: 15, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.84, targetWilaya: "Alger" },
            { specialtyId: "prep-pharma", year: 2025, average: 15.48, targetWilaya: "Boumerdes" },
            { specialtyId: "hygiene", year: 2025, average: 14.9, targetWilaya: "Tizi ouzou" },
            { specialtyId: "hygiene", year: 2025, average: 15.44, targetWilaya: "Alger" },
            { specialtyId: "hygiene", year: 2025, average: 15.2, targetWilaya: "Boumerdes" },
            { specialtyId: "hygiene", year: 2025, average: 15.26, targetWilaya: "Tipaza" },
            { specialtyId: "ass-med", year: 2025, average: 14.5, targetWilaya: "Tizi-ouzou" },
            { specialtyId: "ass-med", year: 2025, average: 15.04, targetWilaya: "Alger" },
            { specialtyId: "ass-med", year: 2025, average: 14.66, targetWilaya: "Boumerdes" },
            { specialtyId: "ass-soc", year: 2025, average: 14.63, targetWilaya: "Blida" },
            { specialtyId: "ass-soc", year: 2025, average: 15.4, targetWilaya: "Alger" },
            { specialtyId: "ass-soc", year: 2025, average: 13.69, targetWilaya: "Boumerdes" },
            { specialtyId: "ass-soc", year: 2025, average: 15.25, targetWilaya: "Tipaza" },
        ]
    },
    {
        id: "infsp-jijel", name: "INFSPM JIJEL", type: "INFSPM", wilaya: "Jijel", location: "Jijel", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "manip-radio", "labo", "prep-pharma", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "kine", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "prep-pharma", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-setif", name: "INFSPM SETIF", type: "INFSPM", wilaya: "Sétif", location: "Sétif", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "ergo", "ortho-app", "psycho", "manip-radio", "labo", "prep-pharma"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.79 },
            { specialtyId: "kine", year: 2025, average: 16.6 },
            { specialtyId: "ergo", year: 2025, average: 15.85 },
            { specialtyId: "ortho-app", year: 2025, average: 16.04 },
            { specialtyId: "psycho", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 16.23 },
            { specialtyId: "labo", year: 2025, average: 16.3 },
            { specialtyId: "prep-pharma", year: 2025, average: 16.06 },
        ]
    },
    {
        id: "infsp-saida", name: "INFSPM SAIDA", type: "INFSPM", wilaya: "Saïda", location: "Saïda", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-skikda", name: "INFSPM SKIKDA", type: "INFSPM", wilaya: "Skikda", location: "Skikda", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "prep-pharma", "hygiene", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "prep-pharma", year: 2025, average: 0 },
            { specialtyId: "hygiene", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-sba", name: "INFSPM SIDI BEL ABBES", type: "INFSPM", wilaya: "Sidi Bel Abbès", location: "Sidi Bel Abbès", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "ergo", "psycho", "manip-radio", "labo", "prep-pharma"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "kine", year: 2025, average: 0 },
            { specialtyId: "ergo", year: 2025, average: 0 },
            { specialtyId: "psycho", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "prep-pharma", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-constantine", name: "INFSPM CONSTANTINE", type: "INFSPM", wilaya: "Constantine", location: "Constantine", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "diet", "kine", "manip-radio", "labo", "prep-pharma", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.53 },
            { specialtyId: "diet", year: 2025, average: 15.89 },
            { specialtyId: "kine", year: 2025, average: 16.53 },
            { specialtyId: "manip-radio", year: 2025, average: 15.95 },
            { specialtyId: "labo", year: 2025, average: 15.83 },
            { specialtyId: "prep-pharma", year: 2025, average: 15.72 },
            { specialtyId: "ass-soc", year: 2025, average: 14.74 },
        ]
    },
    {
        id: "infsp-medea", name: "INFSPM MEDEA", type: "INFSPM", wilaya: "Médéa", location: "Médéa", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "prep-pharma"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "prep-pharma", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-mostaganem", name: "INFSPM MOSTAGANEM", type: "INFSPM", wilaya: "Mostaganem", location: "Mostaganem", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "prep-pharma", "hygiene", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "prep-pharma", year: 2025, average: 0 },
            { specialtyId: "hygiene", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-msila", name: "INFSPM MSILA", type: "INFSPM", wilaya: "M'Sila", location: "M'Sila", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-mascara", name: "INFSPM MASCARA", type: "INFSPM", wilaya: "Mascara", location: "Mascara", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "ergo", "manip-radio", "labo", "hygiene", "ass-med"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "kine", year: 2025, average: 0 },
            { specialtyId: "ergo", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "hygiene", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-ouargla", name: "INFSPM OUARGLA", type: "INFSPM", wilaya: "Ouargla", location: "Ouargla", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "kine", "manip-radio", "labo", "hygiene", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "kine", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "hygiene", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infsp-oran", name: "INFSPM ORAN", type: "INFSPM", wilaya: "Oran", location: "Oran", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "prothese", "prep-pharma", "diet", "kine", "ortho-app", "manip-radio", "labo", "hygiene", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 15.01 },
            { specialtyId: "prothese", year: 2025, average: 16.25 },
            { specialtyId: "prep-pharma", year: 2025, average: 15.72 },
            { specialtyId: "diet", year: 2025, average: 16.5 },
            { specialtyId: "kine", year: 2025, average: 16.4 },
            { specialtyId: "ortho-app", year: 2025, average: 15.53 },
            { specialtyId: "manip-radio", year: 2025, average: 15.79 },
            { specialtyId: "labo", year: 2025, average: 15.8 },
            { specialtyId: "hygiene", year: 2025, average: 15.62 },
            { specialtyId: "ass-med", year: 2025, average: 14.25 },
            { specialtyId: "ass-soc", year: 2025, average: 14.23 },
        ]
    },
    {
        id: "infsp-ain-defla", name: "INFSPM AIN DEFLA", type: "INFSPM", wilaya: "Ain Defla", location: "Ain Defla", bacAverage: 14, description: "Institut National de Formation Supérieure Paramédicale.", specialties: ["isp", "manip-radio", "labo", "ass-med", "ass-soc"], averages: [
            { specialtyId: "isp", year: 2025, average: 0 },
            { specialtyId: "manip-radio", year: 2025, average: 0 },
            { specialtyId: "labo", year: 2025, average: 0 },
            { specialtyId: "ass-med", year: 2025, average: 0 },
            { specialtyId: "ass-soc", year: 2025, average: 0 },
        ]
    },
    {
        id: "infssf-tlemcen", name: "INFSSF TLEMCEN", type: "INFSSF", wilaya: "Tlemcen", location: "Tlemcen", bacAverage: 14, description: "Institut National de Sages-Femmes.", specialties: ["sage-femme"], averages: [
            { specialtyId: "sage-femme", year: 2025, average: 14.57, targetWilaya: "Adrar" },
            { specialtyId: "sage-femme", year: 2025, average: 16.1, targetWilaya: "Chlef" },
            { specialtyId: "sage-femme", year: 2025, average: 14.25, targetWilaya: "Béchar" },
            { specialtyId: "sage-femme", year: 2025, average: 16.23, targetWilaya: "Tlemcen" },
            { specialtyId: "sage-femme", year: 2025, average: 15.82, targetWilaya: "Tiaret" },
            { specialtyId: "sage-femme", year: 2025, average: 15.17, targetWilaya: "Saïda" },
            { specialtyId: "sage-femme", year: 2025, average: 15.88, targetWilaya: "Sidi Bel Abbès" },
            { specialtyId: "sage-femme", year: 2025, average: 15.61, targetWilaya: "Mostaganem" },
            { specialtyId: "sage-femme", year: 2025, average: 16.03, targetWilaya: "Mascara" },
            { specialtyId: "sage-femme", year: 2025, average: 15.67, targetWilaya: "Oran" },
            { specialtyId: "sage-femme", year: 2025, average: 15.26, targetWilaya: "El Bayadh" },
            { specialtyId: "sage-femme", year: 2025, average: 12.69, targetWilaya: "Tindouf" },
            { specialtyId: "sage-femme", year: 2025, average: 15.28, targetWilaya: "Tissemsilt" },
            { specialtyId: "sage-femme", year: 2025, average: 15.19, targetWilaya: "Naâma" },
            { specialtyId: "sage-femme", year: 2025, average: 15.83, targetWilaya: "Aïn Temouchent" },
            { specialtyId: "sage-femme", year: 2025, average: 15.91, targetWilaya: "Relizane" },
            { specialtyId: "sage-femme", year: 2025, average: 13.97, targetWilaya: "Timimoun" },
            { specialtyId: "sage-femme", year: 2025, average: 0, targetWilaya: "Bordj Badji Mokhtar" },
            { specialtyId: "sage-femme", year: 2025, average: 12.45, targetWilaya: "Béni Abbès" },
        ]
    },
    {
        id: "infssf-tizi-ouzou", name: "INFSSF TIZI OUZOU", type: "INFSSF", wilaya: "Tizi Ouzou", location: "Tizi Ouzou", bacAverage: 14, description: "Institut National de Sages-Femmes.", specialties: ["sage-femme"], averages: [
            { specialtyId: "sage-femme", year: 2025, average: 14.62, targetWilaya: "Laghouat" },
            { specialtyId: "sage-femme", year: 2025, average: 14.99, targetWilaya: "Béjaïa" },
            { specialtyId: "sage-femme", year: 2025, average: 15.76, targetWilaya: "Blida" },
            { specialtyId: "sage-femme", year: 2025, average: 15.53, targetWilaya: "Bouira" },
            { specialtyId: "sage-femme", year: 2025, average: 11.93, targetWilaya: "Tamanrasset" },
            { specialtyId: "sage-femme", year: 2025, average: 15.41, targetWilaya: "Tizi Ouzou" },
            { specialtyId: "sage-femme", year: 2025, average: 15.74, targetWilaya: "Alger" },
            { specialtyId: "sage-femme", year: 2025, average: 15.13, targetWilaya: "Djelfa" },
            { specialtyId: "sage-femme", year: 2025, average: 15.93, targetWilaya: "Médéa" },
            { specialtyId: "sage-femme", year: 2025, average: 15.57, targetWilaya: "M'Sila" },
            { specialtyId: "sage-femme", year: 2025, average: 15.79, targetWilaya: "Boumerdès" },
            { specialtyId: "sage-femme", year: 2025, average: 15.54, targetWilaya: "Tipaza" },
            { specialtyId: "sage-femme", year: 2025, average: 15.85, targetWilaya: "Ain Defla" },
            { specialtyId: "sage-femme", year: 2025, average: 15.49, targetWilaya: "Ghardaïa" },
            { specialtyId: "sage-femme", year: 2025, average: 12.42, targetWilaya: "In Salah" },
            { specialtyId: "sage-femme", year: 2025, average: 0, targetWilaya: "In Guezzam" },
            { specialtyId: "sage-femme", year: 2025, average: 14.15, targetWilaya: "El M'Ghair" },
            { specialtyId: "sage-femme", year: 2025, average: 12.92, targetWilaya: "El Meniaa" },
        ]
    },
    {
        id: "infssf-annaba", name: "INFSSF ANNABA", type: "INFSSF", wilaya: "Annaba", location: "Annaba", bacAverage: 14, description: "Institut National de Sages-Femmes.", specialties: ["sage-femme"], averages: [
            { specialtyId: "sage-femme", year: 2025, average: 15.76, targetWilaya: "Oum El Bouaghi" },
            { specialtyId: "sage-femme", year: 2025, average: 16.2, targetWilaya: "Batna" },
            { specialtyId: "sage-femme", year: 2025, average: 15.51, targetWilaya: "Biskra" },
            { specialtyId: "sage-femme", year: 2025, average: 15.28, targetWilaya: "Tébessa" },
            { specialtyId: "sage-femme", year: 2025, average: 15.66, targetWilaya: "Jijel" },
            { specialtyId: "sage-femme", year: 2025, average: 15.97, targetWilaya: "Sétif" },
            { specialtyId: "sage-femme", year: 2025, average: 15.88, targetWilaya: "Skikda" },
            { specialtyId: "sage-femme", year: 2025, average: 15.9, targetWilaya: "Annaba" },
            { specialtyId: "sage-femme", year: 2025, average: 15.88, targetWilaya: "Guelma" },
            { specialtyId: "sage-femme", year: 2025, average: 15.84, targetWilaya: "Constantine" },
            { specialtyId: "sage-femme", year: 2025, average: 14.26, targetWilaya: "Ouargla" },
            { specialtyId: "sage-femme", year: 2025, average: 12.19, targetWilaya: "Illizi" },
            { specialtyId: "sage-femme", year: 2025, average: 15.66, targetWilaya: "Bordj Bou Arreridj" },
            { specialtyId: "sage-femme", year: 2025, average: 15.85, targetWilaya: "El Tarf" },
            { specialtyId: "sage-femme", year: 2025, average: 15.53, targetWilaya: "El Oued" },
            { specialtyId: "sage-femme", year: 2025, average: 15.87, targetWilaya: "Khenchela" },
            { specialtyId: "sage-femme", year: 2025, average: 15.57, targetWilaya: "Souk Ahras" },
            { specialtyId: "sage-femme", year: 2025, average: 15.85, targetWilaya: "Mila" },
            { specialtyId: "sage-femme", year: 2025, average: 13.57, targetWilaya: "Ouled Djellal" },
            { specialtyId: "sage-femme", year: 2025, average: 15.37, targetWilaya: "Touggourt" },
            { specialtyId: "sage-femme", year: 2025, average: 10.15, targetWilaya: "Djanet" },
        ]
    },
];
exports.specialties = [
    { id: "sage-femme", code: "W01SANTE", name: "SAGE FEMME DE SANTE PUBLIQUE", abbreviation: "SAGE-FEMME", duration: "3 à 4 ans", description: "Suivi des grossesses, accouchements et soins obstétricaux.", career: "Maternités, PMI.", subjects: [{ name: "Anatomie Obstétricale", coefficient: 3, credit: 6 }] },
    { id: "isp", code: "X01SANTE", name: "INFIMIERS DE SANTE PUBLIQUE", abbreviation: "ISP", duration: "3 ans", description: "Formation polyvalente pour les soins hospitaliers.", career: "Hôpitaux, cliniques.", subjects: [{ name: "Soins Infirmiers de Base", coefficient: 4, credit: 8 }] },
    { id: "diet", code: "X02SANTE", name: "DIETETICIENS DE SANTE PUBLIQUE", abbreviation: "DIET", duration: "3 ans", description: "Prévention et traitement nutritionnel des maladies.", career: "Hôpitaux, Restauration.", subjects: [{ name: "Nutrition et Diététique", coefficient: 4, credit: 8 }] },
    { id: "prothese", code: "X03SANTE", name: "PROTHESISTES DENTAIRES DE SANTE PUBLIQUE", abbreviation: "PROTH", duration: "3 ans", description: "Conception et fabrication des prothèses dentaires.", career: "Labos dentaires.", subjects: [{ name: "Technologie des Prothèses", coefficient: 4, credit: 7 }] },
    { id: "kine", code: "X04SANTE", name: "KINESITHERAPEUTES DE SANTE PUBLIQUE", abbreviation: "KINE", duration: "3 ans", description: "Rééducation fonctionnelle.", career: "Centres de rééducation.", subjects: [{ name: "Biomécanique", coefficient: 4, credit: 8 }] },
    { id: "podo", code: "X05SANTE", name: "PEDICURE PODOLOGUE DE SANTE PUBLIQUE", abbreviation: "PODO", duration: "3 ans", description: "Soins et traitements des affections du pied.", career: "Cabinets libéraux.", subjects: [{ name: "Pathologies du pied", coefficient: 3, credit: 6 }] },
    { id: "ergo", code: "X06SANTE", name: "ERGOTHERAPEUTES DE SANTE PUBLIQUE", abbreviation: "ERGO", duration: "3 ans", description: "Rééducation par l'activité.", career: "Psychiatrie, Gériatrie.", subjects: [{ name: "Ergothérapie Avancée", coefficient: 4, credit: 7 }] },
    { id: "ortho-app", code: "X07SANTE", name: "APPAREILLEURS ORTHOPEDISTES DE SANTE PUBLIQUE", abbreviation: "ORTHO-APP", duration: "3 ans", description: "Conception et appareillages orthopédiques.", career: "Centres d'appareillages.", subjects: [{ name: "Fabrication d'Ortèses", coefficient: 4, credit: 8 }] },
    { id: "psycho", code: "X08SANTE", name: "PSYCHOMOTRICIENS DE SANTE PUBLIQUE", abbreviation: "PSYCHO", duration: "3 ans", description: "Thérapie des troubles psychomoteurs.", career: "Centres médico-psychologiques", subjects: [{ name: "Développement Psychomoteur", coefficient: 4, credit: 7 }] },
    { id: "manip-radio", code: "X09SANTE", name: "MANIPULATEURS EN IMAGERIE MEDICALE DE SANTE PUBLIQUE", abbreviation: "MIM", duration: "3 ans", description: "Imagerie médicale (Radio, Scanner).", career: "Centres d'imagerie.", subjects: [{ name: "Imagerie Rayons X", coefficient: 4, credit: 7 }] },
    { id: "labo", code: "X10SANTE", name: "LABORANTINS DE SANTE PUBLIQUE", abbreviation: "LABO", duration: "3 ans", description: "Analyses médicales.", career: "Laboratoires.", subjects: [{ name: "Biochimie Clinique", coefficient: 4, credit: 8 }] },
    { id: "prep-pharma", code: "X11SANTE", name: "PREPARATEURS EN PHARMACIE DE SANTE PUBLIQUE", abbreviation: "PREP", duration: "3 ans", description: "Préparation des produits pharmaceutiques.", career: "Pharmacies, hôpitaux.", subjects: [{ name: "Pharmacologie Appliquée", coefficient: 4, credit: 8 }] },
    { id: "hygiene", code: "X12SANTE", name: "HYGIENISTES DE SANTE PUBLIQUE", abbreviation: "HYG", duration: "3 ans", description: "Contrôle de l'hygiène environnementale.", career: "Structures de soins.", subjects: [{ name: "Hygiène Hospitalière", coefficient: 3, credit: 6 }] },
    { id: "ass-med", code: "X13SANTE", name: "ASSISTANTS MEDICAUX DE SANTE PUBLIQUE", abbreviation: "ASS-MED", duration: "3 ans", description: "Assistance dans les processus médicaux.", career: "Cabinets, Urgences.", subjects: [{ name: "Logistique Médicale", coefficient: 3, credit: 5 }] },
    { id: "ass-soc", code: "X14SANTE", name: "ASSISTANTS SOCIAUX DE SANTE PUBLIQUE", abbreviation: "ASS-SOC", duration: "3 ans", description: "Accompagnement social des patients.", career: "Centres sociaux.", subjects: [{ name: "Sociologie de la Santé", coefficient: 3, credit: 6 }] }
];
exports.courses = [];
